name: Create Release

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tools.ps1  # Include your file here (adjust this if you have more files)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update 'latest' release (if exists)
        run: |
          # Check if a release named 'latest' exists, and if so, delete it
          latest_release=$(gh release list --repo re4s0n4/bootstrap | grep "latest" | awk '{print $1}')
          if [ ! -z "$latest_release" ]; then
            gh release delete "$latest_release" --repo re4s0n4/bootstrap --yes
          fi
          # Create a new release named 'latest'
          gh release create latest tools.ps1 --repo re4s0n4/bootstrap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
