name: Create or Update Latest Release

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or Update 'latest' release
        run: |
          # Check if the 'latest' release already exists
          latest_release=$(gh release list --repo re4s0n4/bootstrap | grep "latest" | awk '{print $1}')
          
          if [ -z "$latest_release" ]; then
            echo "Creating a new 'latest' release."
            # If 'latest' doesn't exist, create it with the tools.ps1 file
            gh release create latest tools.ps1 --repo re4s0n4/bootstrap
          else
            echo "Updating the 'latest' release."
            # If 'latest' exists, delete the old one and create a new one with the same name
            gh release delete "$latest_release" --repo re4s0n4/bootstrap --yes
            gh release create latest tools.ps1 --repo re4s0n4/bootstrap
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
